services:
  db:
    image: postgres:alpine
    container_name: iotresto_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - iotresto-network
    restart: always

  api:
    env_file: .env
    image: iotresto:latest
    container_name: iotresto_api
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - iotresto-network
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    restart: always

networks:
  iotresto-network:
